<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('85', '/uploads/14/1-140113112212323.jpg');
$maNum = 1;
$myaddons[$maNum] = array('86', '/uploads/14/1-140113112415W3.jpg');
$maNum = 2;
$myaddons[$maNum] = array('87', '/uploads/2014/1-140113113030930.jpg');
$maNum = 3;
$myaddons[$maNum] = array('88', '/uploads/2014/1-14011312520IF.jpg');
$maNum = 4;
$myaddons[$maNum] = array('89', '/uploads/2014/2014/1-140113125236234.jpg');
$maNum = 5;
