<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('31', '/uploads/allimg/131224/1-1312241Q04L94.jpg');
$maNum = 1;
$myaddons[$maNum] = array('32', '/uploads/allimg/131224/1-1312241Z951P1.jpg');
$maNum = 2;
$myaddons[$maNum] = array('33', '/uploads/allimg/131224/1-131224191259413.jpg');
$maNum = 3;
$myaddons[$maNum] = array('34', '/uploads/allimg/131224/1-131224191259328.jpg');
$maNum = 4;
$myaddons[$maNum] = array('35', '/uploads/allimg/131224/1-131224191602924.jpg');
$maNum = 5;
