<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('37', '/uploads/131226/1-1312261F150493.jpg');
$maNum = 1;
$myaddons[$maNum] = array('38', '/uploads/131226/1-1312261G05M44.jpg');
$maNum = 2;
$myaddons[$maNum] = array('39', '/uploads/131226/1-1312261H004954.jpg');
$maNum = 3;
$myaddons[$maNum] = array('40', '/uploads/131226/1-1312261HU0M1.jpg');
$maNum = 4;
$myaddons[$maNum] = array('41', '/uploads/131226/131226/1-1312261J220549.jpg');
$maNum = 5;
$myaddons[$maNum] = array('42', '/uploads/131226/1-1312261J5342S.jpg');
$maNum = 6;
